Repository Capstone-Team04-AutoScheduler/BE-AutoScheduler, pull requests merged in 2024-11, with the labels that each got.

#58 Feat: 웹크롤링 Safari로 구현
  build.gradle
  src/main/java/Capstone/AutoScheduler/global/config/SecurityConfig.java
  src/main/java/Capstone/AutoScheduler/global/service/SeleniumService/WebCrawlerService.java
  src/main/java/Capstone/AutoScheduler/global/web/controller/CrawlerController.java
Labels: Feature

#59 Feat: 웹크롤링 결과인 html 전체를 string으로 반환하는 API 기능 구현
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/Capstone/AutoScheduler/global/service/SeleniumService/WebCrawlerService.java
  src/main/java/Capstone/AutoScheduler/global/web/controller/CrawlerController.java
Labels: Feature

#60 Refactor: 웹크롤링 chrome에서 수행하도록 수정 및 우분투 ec2서버 chromedriver 설치
  src/main/java/Capstone/AutoScheduler/global/service/SeleniumService/WebCrawlerService.java
  src/main/java/Capstone/AutoScheduler/global/web/controller/CrawlerController.java
Labels: Feature, Refactor

#61 Refactor: chromedriver 설정을 위한 dockerfile 수정
  Dockerfile
  src/main/java/Capstone/AutoScheduler/global/service/SeleniumService/WebCrawlerService.java
Labels: Refactor

#62 Refactor: WebCrawlerService.java 수정
  src/main/java/Capstone/AutoScheduler/global/service/SeleniumService/WebCrawlerService.java
Labels: Refactor

#64 Feat: Generator, Source 엔티티 생성 및, 일정 생성기 저장하는 API 기능 구현
  src/main/java/Capstone/AutoScheduler/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/Capstone/AutoScheduler/global/config/SecurityConfig.java
  src/main/java/Capstone/AutoScheduler/global/converter/GeneratorConverter.java
  src/main/java/Capstone/AutoScheduler/global/domain/entity/Event.java
  src/main/java/Capstone/AutoScheduler/global/domain/entity/Generator.java
  src/main/java/Capstone/AutoScheduler/global/domain/entity/Source.java
  src/main/java/Capstone/AutoScheduler/global/domain/enums/TypeSource.java
  src/main/java/Capstone/AutoScheduler/global/repository/EventRepository.java
  src/main/java/Capstone/AutoScheduler/global/repository/GeneratorRepository.java
  src/main/java/Capstone/AutoScheduler/global/repository/SourceRepository.java
  src/main/java/Capstone/AutoScheduler/global/service/GeneratorService/GeneratorCommandService.java
  src/main/java/Capstone/AutoScheduler/global/service/GeneratorService/GeneratorCommandServiceImpl.java
  src/main/java/Capstone/AutoScheduler/global/service/GeneratorService/GeneratorQueryService.java
  src/main/java/Capstone/AutoScheduler/global/service/GeneratorService/GeneratorQueryServiceImpl.java
  src/main/java/Capstone/AutoScheduler/global/web/controller/EventController.java
  src/main/java/Capstone/AutoScheduler/global/web/controller/GeneratorController.java
  src/main/java/Capstone/AutoScheduler/global/web/controller/MemberController.java
  src/main/java/Capstone/AutoScheduler/global/web/dto/Generator/GeneratorRequestDTO.java
  src/main/java/Capstone/AutoScheduler/global/web/dto/Generator/GeneratorResponseDTO.java
Labels: Feature

#65 Refactor: Dockerfile 수정
  Dockerfile
Labels: Refactor

#67 Feat: 일정 생성기 북마크 설정, 북마크 취소, 사용자가 북마크한 일정 생성기 리스트 조회 API 기능 구현
  src/main/java/Capstone/AutoScheduler/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/Capstone/AutoScheduler/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/Capstone/AutoScheduler/global/config/SecurityConfig.java
  src/main/java/Capstone/AutoScheduler/global/converter/BookmarkConverter.java
  src/main/java/Capstone/AutoScheduler/global/converter/MemberConverter.java
  src/main/java/Capstone/AutoScheduler/global/domain/entity/Bookmark.java
  src/main/java/Capstone/AutoScheduler/global/domain/entity/Generator.java
  src/main/java/Capstone/AutoScheduler/global/domain/entity/Member.java
  src/main/java/Capstone/AutoScheduler/global/repository/BookmarkRepository.java
  src/main/java/Capstone/AutoScheduler/global/service/BookmarkService/BookmarkCommandService.java
  src/main/java/Capstone/AutoScheduler/global/service/BookmarkService/BookmarkCommandServiceImpl.java
  src/main/java/Capstone/AutoScheduler/global/service/GeneratorService/GeneratorCommandServiceImpl.java
  src/main/java/Capstone/AutoScheduler/global/service/MemberService/MemberQueryService.java
  src/main/java/Capstone/AutoScheduler/global/service/MemberService/MemberQueryServiceImpl.java
  src/main/java/Capstone/AutoScheduler/global/web/controller/BookmarkController.java
  src/main/java/Capstone/AutoScheduler/global/web/controller/MemberController.java
  src/main/java/Capstone/AutoScheduler/global/web/dto/Bookmark/BookmarkResponseDTO.java
  src/main/java/Capstone/AutoScheduler/global/web/dto/Member/MemberResponseDTO.java
Labels: Feature

#69 Refactor: EC2 환경에서 크롤링 사용하기 위한 dockerfile 수정
  Dockerfile
Labels: Refactor

#70 Refactor: apt-get 대신 yum 명령어를 사용하여 dockerfile 수정
  Dockerfile
Labels: Refactor

#71 Refactor: Selenium Docker image를 바로 ec2에 설치하여 dockerfile 기존으로 복구
  Dockerfile
Labels: Refactor

#73 Refactor: selenium docker compose내의 연결성 명시 및 github-actions.yml 수정
  .github/workflows/github-actions.yml
  docker-compose.yml
Labels: Refactor

#88 Feat: 일정 생성기 목록 조회 관련 API 기능 구현
  src/main/java/Capstone/AutoScheduler/global/config/SecurityConfig.java
  src/main/java/Capstone/AutoScheduler/global/converter/GeneratorConverter.java
  src/main/java/Capstone/AutoScheduler/global/repository/GeneratorRepository.java
  src/main/java/Capstone/AutoScheduler/global/service/GeneratorService/GeneratorQueryService.java
  src/main/java/Capstone/AutoScheduler/global/service/GeneratorService/GeneratorQueryServiceImpl.java
  src/main/java/Capstone/AutoScheduler/global/web/controller/GeneratorController.java
  src/main/java/Capstone/AutoScheduler/global/web/dto/Generator/GeneratorResponseDTO.java
Labels: Feature

#89 Feature/#87 selenium css
  src/main/java/Capstone/AutoScheduler/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/Capstone/AutoScheduler/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/Capstone/AutoScheduler/global/converter/CrawlingConverter.java
  src/main/java/Capstone/AutoScheduler/global/service/SeleniumService/WebCrawlerService.java
  src/main/java/Capstone/AutoScheduler/global/web/controller/CrawlerController.java
  src/main/java/Capstone/AutoScheduler/global/web/dto/CrawlingResponseDTO.java
Labels: Feature
