Repository Capstone-Team04-AutoScheduler/BE-AutoScheduler, pull requests merged in 2024-12, with the labels that each got.

#91 Feat: 일정 생성기 저장 시 frames, mapping JSON 배열 저장, 웹url 저장 기능 추가
  src/main/java/Capstone/AutoScheduler/global/converter/GeneratorConverter.java
  src/main/java/Capstone/AutoScheduler/global/converter/JsonConverter.java
  src/main/java/Capstone/AutoScheduler/global/domain/entity/Generator.java
  src/main/java/Capstone/AutoScheduler/global/service/GeneratorService/GeneratorCommandService.java
  src/main/java/Capstone/AutoScheduler/global/service/GeneratorService/GeneratorCommandServiceImpl.java
  src/main/java/Capstone/AutoScheduler/global/web/controller/EventController.java
  src/main/java/Capstone/AutoScheduler/global/web/controller/GeneratorController.java
  src/main/java/Capstone/AutoScheduler/global/web/dto/Frame/FrameRequestDTO.java
  src/main/java/Capstone/AutoScheduler/global/web/dto/Frame/FrameResponseDTO.java
  src/main/java/Capstone/AutoScheduler/global/web/dto/Generator/GeneratorRequestDTO.java
  src/main/java/Capstone/AutoScheduler/global/web/dto/Generator/GeneratorResponseDTO.java
Labels: Feature

#92 Feat: 일정 생성기로부터 자동 생성된 모든 일정 저장하는 API 기능 구현
  src/main/java/Capstone/AutoScheduler/global/config/SecurityConfig.java
  src/main/java/Capstone/AutoScheduler/global/converter/EventConverter.java
  src/main/java/Capstone/AutoScheduler/global/service/EventService/EventCommandService.java
  src/main/java/Capstone/AutoScheduler/global/service/EventService/EventCommandServiceImpl.java
  src/main/java/Capstone/AutoScheduler/global/web/controller/EventController.java
  src/main/java/Capstone/AutoScheduler/global/web/dto/Event/EventRequestDTO.java
  src/main/java/Capstone/AutoScheduler/global/web/dto/Event/EventResponseDTO.java
Labels: Feature

#93 Refactor: 자동 생성된 모든 일정 저장하는 API에서 RequestParam으로 받는 부분 PathVariable로 변경(멤버, 일정생성기 Id)
  src/main/java/Capstone/AutoScheduler/global/web/controller/EventController.java
Labels: Feature

#95 Feat: 사용자의 최근 생성된 일정 10개 리스트 조회 API 기능 구현
  src/main/java/Capstone/AutoScheduler/global/config/SecurityConfig.java
  src/main/java/Capstone/AutoScheduler/global/repository/EventRepository.java
  src/main/java/Capstone/AutoScheduler/global/service/EventService/EventQueryService.java
  src/main/java/Capstone/AutoScheduler/global/service/EventService/EventQueryServiceImpl.java
  src/main/java/Capstone/AutoScheduler/global/web/controller/EventController.java
Labels: Feature

#96 Chore: .gitignore 파일 수정
  .gitignore
Labels: Chore

#97 Chore: Remove docker-compose.yml from tracking
  docker-compose.yml
Labels: Chore

#99 feat(): selenium으로 전체 html 크롤링하는 기능 구현
  src/main/java/Capstone/AutoScheduler/global/domain/enums/CrawlingTpye.java
  src/main/java/Capstone/AutoScheduler/global/service/SeleniumService/WebCrawlerService.java
  src/main/java/Capstone/AutoScheduler/global/web/controller/CrawlerController.java
Labels: Feature

#100 Chore: CORS 문제 해결을 위한 설정
  .gitignore
  src/main/java/Capstone/AutoScheduler/global/config/SecurityConfig.java
  src/main/java/Capstone/AutoScheduler/global/config/WebConfig.java
Labels: Chore

#102 Feat: 셀레니움으로 학교 포탈 로그인 후 eclass 메인 페이지 html 반환 API 기능 구현
  src/main/java/Capstone/AutoScheduler/global/config/SecurityConfig.java
  src/main/java/Capstone/AutoScheduler/global/service/SeleniumService/WebCrawlerService.java
Labels: Feature

#105 Refactor: 로그인 후 크롤링 작업 실행할때 GUI 없이 실행하도록 수정
  src/main/java/Capstone/AutoScheduler/global/service/SeleniumService/WebCrawlerService.java
Labels: Refactor

#107 Refactor: 사용자가 북마크한 일정 생성기 조회할때 sourceType 포함한 추가적인 정보 반환하도록 API 수정
  .DS_Store
  src/main/java/Capstone/AutoScheduler/global/converter/MemberConverter.java
  src/main/java/Capstone/AutoScheduler/global/repository/GeneratorRepository.java
  src/main/java/Capstone/AutoScheduler/global/service/GeneratorService/GeneratorQueryService.java
  src/main/java/Capstone/AutoScheduler/global/service/GeneratorService/GeneratorQueryServiceImpl.java
  src/main/java/Capstone/AutoScheduler/global/web/controller/GeneratorController.java
  src/main/java/Capstone/AutoScheduler/global/web/dto/Generator/GeneratorResponseDTO.java
  src/main/java/Capstone/AutoScheduler/global/web/dto/Member/MemberResponseDTO.java
Labels: Refactor

#108 Feat: 전체 일정 생성기 리스트를 조회할때 사용자가 북마크한 생성기를 표시하는 API 기능 구현
  src/main/java/Capstone/AutoScheduler/global/config/SecurityConfig.java
  src/main/java/Capstone/AutoScheduler/global/converter/GeneratorConverter.java
  src/main/java/Capstone/AutoScheduler/global/converter/MemberConverter.java
  src/main/java/Capstone/AutoScheduler/global/repository/BookmarkRepository.java
  src/main/java/Capstone/AutoScheduler/global/service/GeneratorService/GeneratorQueryService.java
  src/main/java/Capstone/AutoScheduler/global/service/GeneratorService/GeneratorQueryServiceImpl.java
  src/main/java/Capstone/AutoScheduler/global/web/controller/GeneratorController.java
Labels: Feature

#110 Feat: 생성된 일정의 색상 지정을 위한 Event 엔티티 컬럼 추가
  src/main/java/Capstone/AutoScheduler/global/converter/EventConverter.java
  src/main/java/Capstone/AutoScheduler/global/domain/entity/Event.java
  src/main/java/Capstone/AutoScheduler/global/web/dto/Event/EventRequestDTO.java
  src/main/java/Capstone/AutoScheduler/global/web/dto/Event/EventResponseDTO.java
Labels: Feature

#111 Feat: 새로운 일정을 생성할때 겹치는 일정이 존재할 경우 예외처리 기능 추가
  src/main/java/Capstone/AutoScheduler/global/repository/EventRepository.java
  src/main/java/Capstone/AutoScheduler/global/service/EventService/EventCommandServiceImpl.java
Labels: Feature

#114 Refactor: 사용자가 일정 생성기 북마크를 삭제하는 API 기능 수정
  src/main/java/Capstone/AutoScheduler/global/config/SecurityConfig.java
  src/main/java/Capstone/AutoScheduler/global/domain/entity/Generator.java
  src/main/java/Capstone/AutoScheduler/global/repository/BookmarkRepository.java
  src/main/java/Capstone/AutoScheduler/global/service/BookmarkService/BookmarkQueryService.java
  src/main/java/Capstone/AutoScheduler/global/service/BookmarkService/BookmarkQueryServiceImpl.java
  src/main/java/Capstone/AutoScheduler/global/web/controller/BookmarkController.java
Labels: Refactor

#115 Refactor: 사용자별 북마크한 일정 생성기 리스트 조회 시 생성기 제작자의 이름을 가져오지 않고 조회한 사용자의 이름을 반환하는 오류 수정
  src/main/java/Capstone/AutoScheduler/global/converter/MemberConverter.java
Labels: Refactor

#117 Feat: 일정 생성기 엔티티에 웹 크롤링시 로그인 필요 여부 컬럼 추가
  src/main/java/Capstone/AutoScheduler/global/converter/GeneratorConverter.java
  src/main/java/Capstone/AutoScheduler/global/converter/MemberConverter.java
  src/main/java/Capstone/AutoScheduler/global/domain/entity/Generator.java
  src/main/java/Capstone/AutoScheduler/global/service/SeleniumService/WebCrawlerService.java
  src/main/java/Capstone/AutoScheduler/global/web/dto/Generator/GeneratorRequestDTO.java
  src/main/java/Capstone/AutoScheduler/global/web/dto/Generator/GeneratorResponseDTO.java
  src/main/java/Capstone/AutoScheduler/global/web/dto/Member/MemberResponseDTO.java
Labels: Feature

#118 Refactor: Unexpected stash error resolved
  src/main/java/Capstone/AutoScheduler/global/service/SeleniumService/WebCrawlerService.java
Labels: Refactor

#120 Refactor: GeneratorRequestDTO 수정
  src/main/java/Capstone/AutoScheduler/global/web/dto/Generator/GeneratorRequestDTO.java
Labels: Refactor
